### ISSUE TITLE
Update the smart contract to support multiple admin users

### ISSUE THREAD

**Issue by philkau** [johnoneworks/saba-future#26]
## Tasks:

- [x] Add the function to add admin user
- [x] Add the function to remove admin user
- [x] Add the function to check the address is admin or not
- [x] Add the require functions to limit the admin user
- [x] Add the unit tests for multiple admin users

## Unit Tests:

- Owner should be the default admin
- Should be rejected to update the admin user if user is NOT owner
- Should update the admin users if the user is owner
- Should be rejected to create a market if the user is NOT admin user
- Should create the market when the user is admin user
- Should be rejected to distribute if the user is NOT admin user
- Should distribute when the user is admin user
